config/routes.rb
Allaboard::Application.routes.draw do

  root  'static_pages#new_home'

  get 'boards/suggest', to: 'boards#suggestion'
  post 'boards/suggestion/create', to: 'boards#suggestion_create'
  devise_for :users
  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  post '/contact/send', to: 'static_pages#send_contact_message'
  match '/existing', to: 'static_pages#existing_members', via: 'get'
  match '/interested', to: 'static_pages#interested_member', via: 'get'
  match '/new_home', to: 'static_pages#new_home', via: 'get'
  match '/community', to: 'static_pages#community', via: 'get'

  resources :users
  resources :parent_organizations do
    collection do
      post 'import'
    end
  end

  resources :reviews, only: [:new, :create]
  resources :events, only: [:index, :show], param: :slug
  resources :reviews
  #resources :comments, :only => [:destroy, :show, :edit, :update]

  resources :articles, param: :slug do
    resources :comments, :only => [:create, :new]
  end

  resources :categories
  resources :announcements, only: [:index]

  resources :boards, param: :slug do
    resources :reviews, only: [:index, :show, :new]
    resources :events, param: :slug
    resources :announcements
    get 'claim'
    get 'unclaim'
    post 'assign'
    post 'unassign'
  end

  resources :vendors
  resources :vendor_reviews

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  #layout "home"

  def home
    @events = Event.where("date >= ?", Date.today).order('date').limit(5)
    @announcements = get_all_announcements_created_over_the_past_month
    @new_boards = get_all_boards_claimed_this_week
    @new_events = get_all_events_created_this_week
    @recent_articles = get_five_most_recent_articles
  end

  def new_home
    @contact = Contact.new
  end

  def community
  end

  def contact
    @contact = Contact.new
  end

  def existing_members
  end

  def interested_member
  end

  def send_contact_message
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash[:error] = nil
      flash[:notice] = 'Thank you for your message!'
      redirect_to root_path
    else
      flash[:error] = 'Cannot send message.'
      render :contact
    end
  end

  private
  def get_all_boards_claimed_this_week
    boards = Board.where("user_id is not null and claim_date >= ?", Time.now.beginning_of_week)
  end

  def get_all_events_created_this_week
    events = Event.where("created_at >= ?", Time.now.beginning_of_week)
  end

  def get_all_announcements_created_over_the_past_month
    announcements = Announcement.where("created_at >= ?",Time.now.last_month).order('created_at DESC').limit(5)
  end

  def get_five_most_recent_articles
    articles = Article.where("created_at >= ?",Time.now.last_month).order("created_at DESC").limit(5)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_contact_form.html.erb
<%= form_for @contact, :url => contact_send_path do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.text_field :name, :placeholder=>"Your Name *", :id=>"name", class:"form-control"%>
        <p class="help-block text-danger"></p>
      </div>

      <div class="form-group">
        <%= f.text_field :email, :placeholder=>"Your Email *", :id=>"email", class:"form-control"%>
        <p class="help-block text-danger"></p>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.text_area :message, :placeholder=>"Your Message *", :id=>"message", :rows=>4, :class=>'form-control' %>
        <p class="help-block text-danger"></p>
      </div>
    </div>
    <div class="clearfix"></div>
    <div class="col-lg-12 text-center">
        <div id="success"></div>
        <%= f.submit "Send Message", class: "btn btn-xl" %>
    </div>

<% end %>

app/views/static_pages/_mailchimp_form.html.erb
<div class="row">
  <div>
    <form action="//allaboardalliance.us9.list-manage.com/subscribe/post?u=9b95903b7918c7b171cd89ba1&amp;id=8e249e7331" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate form-inline" target="_blank" novalidate>
      <div class="form-group">
        <label for="mce-EMAIL" class="sr-only">Email Address</label>
        <input type="email" value="" name="EMAIL" class="form-control input-lg" placeholder="Your Email Address" id="mce-EMAIL">
      </div>
      <button type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary btn-lg">Subscribe</button>
    </form>
  </div>
</div>

app/views/static_pages/about.html.erb
<div class="container">
	<div class="row">
		<div class="span7 mycontent-left">
			<div class="row">
				<div class="span7 content-header">
					<span class="lead"><strong>About Us</strong></span>
				</div>
			</div>

			<div class="row">
				<div class="span7">
					<p class="section-title">Purpose</p>
						<p>As associate boards and other non-governing boards have become integrated into many nonprofit organizations’ strategic plans, it only makes sense to create a community for these boards to come together and share resources. Many boards have an abundance of talent and energy, but lack resources for board growth and development. Our goal is to create a space (both virtual and in-person) that brings non-governing boards together to share ideas, gain knowledge, and foster support and enthusiasm for the work achieved by these boards.</p>
						<p>Ultimately, we want to enable peer learning.</p>
				</div>
			</div>

			<div class="row">
				<p>&nbsp;</p>
			</div>

			<div class="row">
				<div class="span7">
					<p class="section-title">Background</p>
						<p>All A-Board Alliance was established in April 2014 when six members of various associate boards met at Open Books on Chicago's Near North Side. They quickly agreed on a vision for the alliance and began working to bring it to life.
						The task of naming the alliance proved to be challenging, as multiple names exist for boards with similar goals (associate board, auxiliary boards, junior boards, young professional boards etc). In an effort to be inclusive and show we have a sense of humor, the steering committee chose All A-Board Alliance as the name. This was intended to embody the notion that we aim to bring together all non-governing boards.</p>
				</div>
			</div>

			<div class="row">
				<p>&nbsp;</p>
			</div>

			<div class="row">
				<div class="span7">
					<p class="section-title">Structure</p>
						<p>Because this community is comprised of individuals who already have numerous meetings on their agenda, we respect the limited availability of our members. We designed the alliance to foster communication virtually and through minimal (quarterly) meetings. Further, we intend to have topic-oriented meetings which will allow members to determine in advance whether the meeting will provide value for them (e.g. Mission Drafting and Recruiting Founding Members may be relevant for new boards, but not for more established boards).</p>
						<p>Each quarter a different nonprofit organization will host the meeting. Experts may be brought in to present on topics at the meetings; however the primary focus will be allowing members to engage in group discussion to help overcome their boards’ unique challenges, brainstorm new strategies, and share resources. </p>
				</div>
			</div>
		</div>
		<div class="span4">
			<div class="row">
				<p><span class='lead'>Steering Committee</span></p>
				<p>All A-Board Alliance is overseen by a team of volunteers who have experience creating and/or serving on associate boards.</p>
				<%= image_tag "35b532e.jpg", class: "img-circle", alt: "Elizabeth Fu"  %><strong>Elizabeth Fu</strong>
				<%= image_tag "3000e10.jpg", class: "img-circle", alt: "Sarah Hurwit"  %><strong>Sarah Hurwit</strong>
				<%= image_tag "IMG_7006.jpg", class: "img-circle", alt: "Lauren King"  %><strong>Lauren King</strong>
				<%= image_tag "475192.jpg", class: "img-circle", alt: "Elizabeth Slawin"  %><strong>Elizabeth Slawin</strong>
				<%= image_tag "alnierys-venegas.jpg", class: "img-circle", alt: "Alnierys Venegas"  %><strong>Alnierys Venegas</strong>
				<%= image_tag "1e7c92e.jpg", class: "img-circle", alt: "Warren Yates"  %><strong>Warren Yates</strong>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/community.html.erb
<% provide(:title, "Our Community:") %>
<% provide(:nav_title1, "Home") %>
<% provide(:nav_link1, root_path) %>
<% provide(:nav_title2, "Prospective") %>
<% provide(:nav_link2, "#prospective") %>
<% provide(:nav_title3, "Current") %>
<% provide(:nav_link3, "#existing") %>
<% provide(:nav_title4, "Nonprofits") %>
<% provide(:nav_link4, "#nonprofits") %>

<!-- Header -->
<header style="background-image: url('<%=asset_path('community-header-bg.png')%>');"> <!-- Need new image -->
    <div class="container">
      <div class="intro-text">
      </div>
    </div>
</header>

<!-- Prospective Members Section -->
<section id="prospective" >
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Prospective Associate Board Members</h2>
                <h3 class="section-subheading text-muted">Get involved with an Associate Board.</h3>
            </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-sm-6 text-center">
              <h2 class="text-right">What is an Associate Board?</h2>
          </div>

          <div class="col-md-8 text-justify">
            <blockquote>
                <p class="large text-muted">Junior Board, Young Professionals Board, Associate Board, Auxiliary Board.</p>
                <p class="large text-muted">The names may very, but they all have a similar purpose. These groups exist to provide support to nonprofit organizations. Most often this is done through philanthropic support (hosting fundraisers) and through advocacy (serving as ambassadors for the organization's mission).</p>
                <p class="large text-muted">As these types of boards have grown in popularity, so too has the opportunity for young professionals to get involved.</p>
            </blockquote>
          </div>
        </div>

        <div class="row">
          <div class="col-md-4 col-sm-6 ">
          </div>

          <div class="col-md-8 col-sm-12 portfolio-item">
            <div class="portfolio-caption">
              <h4 class="text-center">Three Reasons to join an Associate Board:</h4>
              <div class="col-md-4 col-sm-6 portfolio-item">
                <%= image_tag "new-skills.png", class:"img-responsive", alt: "Learn new shills" %>
                <div class="portfolio-caption">
                  <h5 class="text-center text-muted">Develop and Practice skills that you don't get to use at work.</h5>
                </div>
              </div>
              <div class="col-md-4 col-sm-6 portfolio-item">
                <%= image_tag "community-leadership.png", class:"img-responsive", alt: "Community Leadership" %>
                <div class="portfolio-caption">
                  <h5 class="text-center text-muted">Serve the community and build leadership skills.</h5>
                </div>
              </div>
              <div class="col-md-4 col-sm-6 portfolio-item">
                <%= image_tag "networking.png", class:"img-responsive", alt: "Networking" %>
                <div class="portfolio-caption">
                  <h5 class="text-center text-muted">Grow your network in meaningful way. Work alongside professionals outside of your field.</h5>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-lg-12">
              <h2 class="text-left">Here are ways to get started.</h2>

              <div class="col-md-4 col-sm-6 portfolio-item">
                <div class="portfolio-caption">
                  <h4 class="text-center"><%= link_to "Find the board for you", boards_path %></h4>
                </div>
                <div class="portfolio-caption">
                  <p class="text-justify text-muted">Browse through our directory of Associate Boards.
                    Check out their board profiles, and reach out to the board representatives to inquire about opportunities to get involved.</p>
                </div>
              </div>

              <div class="col-md-4 col-sm-6 portfolio-item">
                <div class="portfolio-caption">
                  <h4 class="text-center"><%= link_to "Attend an event", events_path %></h4>
                </div>
                <div class="portfolio-caption">
                  <p class="text-justify text-muted">Attend an event that is put on by local Associate Boards. Look our events page to see list of upcoming events.</p>
                </div>
              </div>

              <div class="col-md-4 col-sm-6 portfolio-item">
                <div class="portfolio-caption">
                  <h4 class="text-center"><%= link_to "Get our newsletter", "http://www.charityscenes.org", target: "_blank"%> <i class="fa fa-external-link"></i></h4>
                </div>
                <div class="portfolio-caption">
                  <p class="text-justify text-muted">Sign up for bi-monthly CharityScenes newsletter highlighting non-profit events for young professionals.</p>
                </div>
              </div>

          </div>
        </div>
    </div>
</section>

<!-- Existing Nonprofits Aside -->
<aside class="clients">
    <div class="container">
      <div class="row">
          <div class="col-lg-12 text-center">
              <h3 class="section-subheading text-muted">Some Community nonprofit organizations with associate boards</h3>
          </div>
      </div>
        <div class="row text-center">
          <div class="col-md-4 col-sm-4">
              <%= link_to (image_tag 'big-brothers-big-sisters-chicagologo.png', alt: "Big Brothers Big Sisters Associate Board"), "http://www.bbbschgo.org/site/c.bkLUKcOVLkK2E/b.6448163/k.8D0F/Leadership_Board.htm", target: "_blank" %>
          </div>
          <div class="col-md-2 col-sm-3">
              <%= link_to (image_tag 'american-cancer-society-logo.png', alt: "Amercian Cancer Soceity Associate Board"), "http://www.acsaboa.org/", target:"_blank" %>
          </div>
          <div class="col-md-2 col-sm-3">
            <%= link_to (image_tag 'shedd-aquarium-logo.png', alt: "Shedd Aquarium Auxiliary Board"), "http://www.sheddaquarium.org/Support-Us/Auxiliary-Board/", target:"_blank" %>
            </a>
          </div>
          <div class="col-md-4 col-sm-3">
            <a href="#">
              <%= link_to (image_tag 'center-for-economic-progress-logo.png', alt:"Center for Economic Progress Associate Board"), "http://www.economicprogress.org/about/our-team", target:"_blank" %>
            </a>
          </div>
        </div>
    </div>
</aside>

<!-- Existing Members Section -->
<section id="existing" class="bg-light-gray">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Current Associate Board Members</h2>
                <h3 class="section-subheading text-muted">Enhance your Associate Board Experience.</h3>
            </div>
        </div>

        <div class="row">
          <div class="col-md-8 text-justify">
            <blockquote class="blockquote-reverse">
                <p class="large text-muted">We interact with many different group but our primary focus will always be on serving associate boards. When your board chooses to join our community, it represents a partnership between you and us.</p>
                <p class="large text-muted">Although many associate boards have been functioning successfully on our own, we think we all stand to improve by coming together. The All A-Board Alliance aims to help strengthen boards so they can better meet their goals, as well as help ensure that associate board service provides a meaningful experience for young professionals.</p>
            </blockquote>
          </div>

          <div class="col-md-4 col-sm-6 text-center">
              <h2 class="text-left">Why join our community?</h2>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
              <h2 class="text-right">Maximize your Involvement with our Community</h2>
          </div>
          <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="portfolio-caption">
              <h4 class="text-center"><%= link_to "Use the resources", new_home_path(:anchor => "portfolio") %></h4>
            </div>
            <div class="portfolio-caption">
              <p class="text-justify text-muted">From strategic planning to vendor lists to ideas for upcoming fundraisers, we’ve got it all. But they are only useful if you remember to use them. We encourage you to share these resources with your fellow board members too.</p>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="portfolio-caption">
              <h4 class="text-center"><%= link_to "Share your knowledge", articles_path %></h4>
            </div>
            <div class="portfolio-caption">
              <p class="text-justify text-muted">Providing additional information and resources, such as how-to articles, links to free service providers, or even a blog post about lessons learned from your most recent fundraiser, is a welcome gesture that helps the community remain strong and vibrant.</p>
            </div>
          </div>

          <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="portfolio-caption">
              <h4 class="text-center"><%= link_to "Attend our events", events_path %></h4>
            </div>
            <div class="portfolio-caption">
              <p class="text-justify text-muted">We use our events primarily to surface and address problems affecting the AB community, but these are also opportunities for ABs to meet each other and hopefully form new collaborations!</p>
            </div>
          </div>


        </div>
    </div>
</section>

<!-- Existing Members Section -->
<section id="nonprofits">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Nonprofit Organizations</h2>
                <h3 class="section-subheading text-muted">How can Associate Boards help you?</h3>
            </div>
            <div class="col-md-4 col-sm-6 text-center">
                <h2 class="text-right">Embrace the power of an Associate Board</h2>
            </div>

            <div class="col-md-8 text-justify">
              <blockquote>
                  <p class="large text-muted">Much of an associate board's success is contingent on the support of the parent organization, i.e. the nonprofit whose mission is supported by the associate board. This is because the associate board, or AB, can only do what its parent nonprofit allows it to do. </p>
              </blockquote>
            </div>

        </div>
    </div>
</section>

app/views/static_pages/contact.html.erb
<div class="container">
	<div class="row">
		<div class="span7 mycontent-left">
			<div class="row">
				<div class="span7 content-header">
					<span class="lead"><strong>Contact Us</strong></span>
				</div>
			</div>	
			
			<div class="row">
				<div class="span7">
					<p>Use this form to contact a member of our steering committee.</p>
				</div>
			</div>	
			
			<div class="row">
				<div class="span7">
					<%= form_for @contact, :url => contact_send_path do |f| %>
						<div class="form-group">		
							<% if @contact.errors.any? %>
				  				<div id="error_explanation">
				    				<div class="alert alert-error">
				      					The form contains <%= pluralize(@contact.errors.count, "error") %>.
				    				</div>
				    				<ul>
				    					<% @contact.errors.full_messages.each do |msg| %>
				      						<li>* <%= msg %></li>
				    					<% end %>
				    				</ul>
				  				</div>
							<% end %>
				
							<div class="row">
								<div class="span6"><%= f.label :name, 'Your Name'%></div>
							</div>
	
							<div class="row">		
								<div class="span6"><%= f.text_field :name, :placeholder=>"John Smith" %></div>
							</div>
				
							<div class="row">
								<div class="span6"><%= f.label :Email, 'Your email address'%></div>
							</div>

							<div class="row">		
								<div class="span6"><%= f.text_field :email, :placeholder=>"you@example.com" %></div>
							</div>	

							<div class="row">
								<div class="span6"><%= f.label :message, 'Message'%></div>
							</div>							
			
							<div class="row">
								<div class="span6"><%= f.text_area :message, :placeholder=>"Your message to us", :rows=>4, :class=>'input-block-level', :autofocus=> true %>
							</div>
						</div>
				
		        		<%= f.hidden_field :nickname, :hint => 'Leave this field blank!' %>
		
						<div class="row">	
							<div class="span6"><%= f.submit "Send", class: "btn btn-primary" %>&nbsp;<%= link_to 'Cancel', root_path %></div>
						</div>
					</div>
				<% end %>
			</div>
		</div></div>
		<div class="span4">
			<div class="row">
				<%= image_tag 'AAA_Logo.png' %>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/existing_members.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-7 mycontent-left">
			<div class="row">
				<div class="col-lg-7 content-header">
					<span class="lead"><strong>Enhance your Associate Board Experience</strong></span>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-7">
					<h4>Connect</h4>
									<p>Check out our curated list of <%= link_to 'Associate Boards', boards_path %>. This directory offers a list of associate boards around Chicago, along with a description of their mission. Enabling us to find each other.<blockquote><em>When we have a better way to connect with one another, then partnerships can start to develop.</em></blockquote></p>
									<h4>Communicate</h4>
									<p>Let's borrow ideas from one another and also plan strategically. Browse through our up-to-date <%= link_to 'listing of events', events_path %> among all boards. Get ideas for your next event or partner up to make your event have a bigger impact.</p>
									<p><em>Have thoughts and feedback for a board?</em> <%= link_to 'Leave confidential reviews', new_review_path %> for boards to gain honest feedback about their performance.</p>
									<h4>Collaborate</h4>
									<p>Resource sharing is an important tool for enhancing the outcomes of work done by associate boards.  <em>Why re-create the wheel each time you do an event?</em> Look through our <%= link_to 'resources library', articles_path %> for “How to” guides as well as reviews of local vendors and venues that have been used by our members.</p>
				</div>
			</div>
		</div>
		<div class="col-lg-2">
			<div class="row">
				<%= image_tag 'AAA_Logo.png' %>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>
</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Chicago's Associate Boards:") %>

<div id="myCarousel" class="carousel slide">
	<!-- Carousel items -->
  	<div class="carousel-inner">
    	<div class="active item">
			<%= image_tag "slide-01.jpg" %>
			<div class="container">
				<div class="carousel-caption">
		    		<h1>Welcome to Chicago's Associate Board community.</h1>
					<p class="lead">We are creating a community to strengthen the impact of Associate Boards around Chicago.</p>
		   		</div>
			</div>
    	</div>
    	<div class="item">
			<%= image_tag "slide-02.jpg" %>
			<div class="container">
				<div class="carousel-caption">
		    		<h1>Already an Associate Board member?</h1>
					<p class="lead">Check out our curated list of associate boards, browse through our up-to-date listing of events, or look through our resources library to for "How to" guides and best practices. </p>
		        	<%= link_to ' Learn more', existing_path, class: "btn btn-large btn-primary" %>
		   		</div>
			</div>
    	</div>
    	<div class="item">
			<%= image_tag "slide-03.jpg" %>
			<div class="container">
				<div class="carousel-caption">
		    		<h1>Want to get involved with an Associate Board?</h1>
					<p class="lead">Browse through our up-to-date listing of events and join us at one of our quarterly meetups. </p>
		        	<%= link_to ' Learn more', interested_path, class: "btn btn-large btn-primary" %>
		   		</div>
			</div>
    	</div>
  	</div>
  	<!-- Carousel nav -->
  	<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
  	<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
</div>

<div class="container">
	<div class="row">
		<div class="span12">
			<div class="span7 mycontent-left-no-border">
				<h3>Recent Updates</h3>
				<% if !@new_boards.blank? %>
					<p><span class="label label-info">Boards</span>&nbsp; <%= pluralize(@new_boards.count, 'board') %> claimed this week.</p>
					<% @new_boards.each do |new_board| %>
						<p><%= link_to new_board.name, board_path(new_board.slug) %><br />
							<small><span class="text-info">Contact: <%= mail_to new_board.user.email, new_board.user.get_name, encode: "hex", subject: "About your board on the All ABoard Alliance." %></span></small></p>
						<% if new_board == @new_boards.last %>
  							</p>	<hr />
  						<% end %>
					<% end %>
				<% end %>
				
				<% if !@new_events.blank? %>
					<p><span class="label label-info">Events</span>&nbsp; <%= pluralize(@new_events.count, 'event') %> added this week.</p>
					<% @new_events.each do |new_event| %>
						<p><%= link_to new_event.name, event_path(new_event.slug)  %> <br />
							<small><span class="text-info">Submitted by <%= link_to new_event.board.name, board_path(new_event.board.slug) %></span></small></p>
						<% if new_event == @new_events.last %>
  							</p>	<hr />
  						<% end %>
					<% end %>
				<% end %>
				
				<% if !@announcements.blank? %>
					<% @announcements.each do |announcement| %>
						<p><span class="label label-info">Announcement</span><%= announcement.text.html_safe %>
						<small><span class="text-info">By: <%= link_to announcement.board.name, board_path(announcement.board.slug) %> | Submitted <%= time_ago_in_words(announcement.created_at) %> ago.</span></small></p>
						<hr />
					<% end %>
				<% end %>
				
				<% if !@recent_articles.blank? %>
					<% @recent_articles.each do |recent_article| %>
						<p><span class="label label-info">KB Article</span>&nbsp; <strong><%= link_to recent_article.title.html_safe, article_path(recent_article.slug) %></strong><br />	
						<small><span class="text-info">Published: <%= time_ago_in_words(recent_article.created_at) %> ago by <%= mail_to recent_article.user.email, recent_article.user.get_name, encode:"hex", subject: "About your KB article on All ABoard Alliance.", body: "I read through your Knowledge Base article on " + recent_article.title.html_safe + "and I wanted to reach out to you about it."%>.</span></small></p>
						
						
						
						<% if recent_article != @recent_articles.last %>
  								<hr />
  						<% end %>
					<% end %>
				<% end %>
				
			</div>
			<div class="span4 pull-right">
				<div class="row">
					<div>
						<%= image_tag 'AAA_Logo.png' %>
						
						<a class="twitter-timeline" 
						   href="https://twitter.com/ABoardAlliance" 
						   data-widget-id="515968580030963712"
  						   width="300"
						   height="500"
						   target="_blank">
						Tweets by @ABoardAlliance</a>
					</div>
					
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="span12 row-separator pull-right">
		</div>
	</div>
	
	<div class='row'>
		<div class="span12">
			<div class="span8 pull-left">
				<h3>Upcoming Events</h3>
			</div>
			<div class="span3 pull-right">
				<h3 class="text-right"><%= button_to 'See All Events', events_path, class: "btn btn-link", method: 'get' %> </h3>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="span12 pull-right">
			<% if !@events.blank? %>
				<table class="table">
					<tbody>
						<% @events.each do |event| %>
							<tr>
								<td width="80%"><h4><%= link_to event.name, event_path(event.slug) %></h4></td>
								<td width="20%"><strong><%= event.date.strftime("%B %d, %Y") %></strong></td>
							</tr>
						<% end %>
					</tbody>
				</table>
			<% else %>
				<p>There are no currently no planned events. </p>
			<% end %>
		</div>
	</div>
</div>

<script  type="text/javascript">
// call the flippyNum function
/*flippyNum(document.getElementById('flippy'), {
									startNumber: $('#flippy').data('value'),
									endNumber:  $('#flippy').data('value'),
									digits: $('#flippy').data('size'),
										imagePath: '/assets/flippyNum.png',
										width: 29,
										height: 40
										}
									);
*/
	!function ($) {
        $(function(){
          // carousel demo
          $('#myCarousel').carousel()
        })
      }(window.jQuery)
	
	!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");

</script>

app/views/static_pages/interested_member.html.erb
<div class="container">
	<div class="row">
		<div class="span7 mycontent-left">
			<div class="row">
				<div class="span7 content-header">
					<span class="lead"><strong>Get Involved with an Associate Board</strong></span>
				</div>
			</div>
			
			<div class="row">
				<div class="span7">
					<p>Junior Board, Young Professionals Board, Associate Board, Auxiliary Board....the names may very, but they all have a similar purpose. These groups exist to provide support to nonprofit organizations. Most often this is done through philanthropic support (hosting fundraisers) and through advocacy (serving as ambassadors for the organization's mission). As these types of boards have grown in popularity, so too has the opportunity for young professionals to get involved.<p>
					<p> Thinking of joining a board? Here are some top reasons why it may be right for you:
						<ul>
						<li>Opportunity to develop and practice skills you don't get to use at work (e.g- event planning, finance, volunteer management).</li>
						<li>Unique opportunity to serve the nonprofit community and also build leadership skills.</li>
						<li>A chance to grow your network in meaningful way- you get to know and work alongside other professionals outside of your own field.
						<li>Board membership at the junior level can prepare you to serve on a Board of Directors in the future.</li>
						</ul>
					</p>
					<p>See <%= link_to 'our directory', boards_path %> for descriptions of local board opportunities.</p>
				</div>
			</div>
		</div>
		<div class="span3">
			<div class="row">
				<%= image_tag 'AAA_Logo.png' %>
				<p>&nbsp;</p>
			</div>
		</div>
	</div>
</div>