config/routes.rb
Allaboard::Application.routes.draw do

  root  'static_pages#new_home'

  get 'boards/suggest', to: 'boards#suggestion'
  post 'boards/suggestion/create', to: 'boards#suggestion_create'
  devise_for :users
  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  post '/contact/send', to: 'static_pages#send_contact_message'
  match '/existing', to: 'static_pages#existing_members', via: 'get'
  match '/interested', to: 'static_pages#interested_member', via: 'get'
  match '/new_home', to: 'static_pages#new_home', via: 'get'
  match '/community', to: 'static_pages#community', via: 'get'

  resources :users
  resources :parent_organizations do
    collection do
      post 'import'
    end
  end

  resources :reviews, only: [:new, :create]
  resources :events, only: [:index, :show], param: :slug
  resources :reviews
  #resources :comments, :only => [:destroy, :show, :edit, :update]

  resources :articles, param: :slug do
    resources :comments, :only => [:create, :new]
  end

  resources :categories
  resources :announcements, only: [:index]

  resources :boards, param: :slug do
    resources :reviews, only: [:index, :show, :new]
    resources :events, param: :slug
    resources :announcements
    get 'claim'
    get 'unclaim'
    post 'assign'
    post 'unassign'
  end

  resources :vendors
  resources :vendor_reviews

end

app/models/article.rb
class Article < ActiveRecord::Base
  
  validates :title, presence: true
  validates :body, presence: true
  validates :slug, presence: true, uniqueness: { case_sensitive: false }
  
  belongs_to :user
  has_many :comments
  
  before_validation :create_slug
  

  
  
  private
    def create_slug
      self.slug = title.parameterize
    end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :edit, :destroy]

  def index    
    @articles = Article.order("created_at DESC")
  end
  
  def show
    @article = Article.find_by(slug: params[:slug])
    @comments = @article.comments.order("created_at DESC")
  end

  def new
    if site_admin_logged_in? 
      @article = Article.new   
    else
      redirect_to articles_path, notice: "Only site admins can post Knowledge Base articles."
    end
    
  end

  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      redirect_to articles_path, notice: "The article has been successfully created."
    else
      render action: "new"
    end
  end
  
  def edit
    @article = Article.find_by(slug: params[:slug])
    if !site_admin_logged_in?
      redirect_to article_path(@article.slug), notice: "Only site admins can edit this Knowledge Base articles."
    end
  end

  def update
    @article = Article.find(params[:slug])
    if @article.update_attributes(article_params)
      redirect_to article_path(@article.slug), notice: "The article has been successfully updated."
    else
      render action: "edit"
    end
  end
  
  
  private

    def article_params
      params.require(:article).permit(:title, :body)
    end
    
    
  
  
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_error_messages.html.erb
<% if @article.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
		      The form contains <%= pluralize(@article.errors.count, "error") %>.
		</div>
  		<ul>
    		<%= @article.errors.full_messages.each do |message| %>
        		<li>* <%= message %></li>
    		<% end %>
  		</ul> 
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
	<div class="form-group">
		<%= render 'error_messages' %>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :title, 'Post Title'%>
					<%= f.text_field :title, :placeholder=>"Clever title for your post.", class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8 col-sm-6">
				<div class="form-group">
					<%= f.label :body, 'Post Body'%>
					<%= f.cktext_area :body, rows: 10, :class=>'input-block-level', class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="clearfix"></div>

		<div class="row">
			<div class="col-md-6">
				<%= f.submit "Save", class: "btn btn-primary" %> <%= link_to 'Cancel', articles_path %>
			</div>
		</div>
	</div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "Edit post:") %>
<%= render 'shared/header' %>

<section>
	<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 class="section-heading">Edit Post</h3>
      </div>
    </div>

		<div class="row text-muted">
			<div class="col-lg-12">
			     <p>Use the form below to edit this post.</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
				<% if site_admin_logged_in? %>
					<%= render 'form'%>
				<% else %>
					<p>Sorry, only the All A-Board Alliance administrators can add a board. This is how we can maintain a carefully curated list of boards.<br /> If you would like to suggest a board to add, please <%= link_to "tell us about it", boards_suggest_path %>.</p>
				<% end %>
			</div>
		</div>

	</div>
</section>

app/views/articles/index.html.erb
<% provide(:title, "Resources for Chicago's Associate Boards:") %>
<%= render 'shared/header' %>

<section>
	<div class="container">
    <div class="row text-center">
      <div class="col-lg-12">
        <h2 class="section-heading">All A-Board Blog & Resources</h2>
      </div>
    </div>
		<div class="row text-muted">
			<div class="col-lg-12 text-center">
			     <p>This is a listing of resources and articles that we have collected from the community.</p>
			</div>
		</div>
		<div class="row">
      <div class="col-md-8 mycontent-left">
				<% if !@articles.blank? %>
					<% @articles.each do |article| %>
  						<p><strong><%= link_to article.title.html_safe, article_path(article.slug) %></strong><br />
						<small><span class="text-info">Published: <%= time_ago_in_words(article.created_at) %> ago by <%= article.user.get_name %>.</span></small></p>
  						<p><%= article.body.truncate(500, separator:' ').html_safe %><br />
<p><%= link_to 'more', article_path(article.slug)  %></p>
  						<% if article != @articles.last %>
  							<hr />
  						<% end %>
					<% end %>
				<% end %>
			</div>
			<div class="col-md-3">
        <div class="row">
					<h5>More Resources</h5>
					<p><%= link_to 'Event Space Directory', vendors_path %></p>
					<p>Templates</p>
				</div>
				<div class="row">
					<% if site_admin_logged_in? %>
						<p><strong>Admin Options</strong><br />
							<%= link_to "Post new article", new_article_path %>
						</p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/articles/new.html.erb
<% provide(:title, "Add a post:") %>
<%= render 'shared/header' %>

<section>
	<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 class="section-heading">Add a new post</h3>
      </div>
    </div>

		<div class="row text-muted">
			<div class="col-lg-12">
			     <p>Use the form below to add a new post to the blog & resources page.</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
				<% if site_admin_logged_in? %>
					<%= render 'form'%>
				<% else %>
					<p>Sorry, only the All A-Board Alliance administrators can add a board. This is how we can maintain a carefully curated list of boards.<br /> If you would like to suggest a board to add, please <%= link_to "tell us about it", boards_suggest_path %>.</p>
				<% end %>
			</div>
		</div>

	</div>
</section>

app/views/articles/show.html.erb
<% provide(:title, @article.title.html_safe + ": ") %>
<%= render 'shared/header' %>

<section>
	<div class="container">
		<div class="col-md-12 ">
			<h2 class="section-heading"><%= @article.title.html_safe %></h2>
			<p class="text-info"><small>Published: <%= time_ago_in_words(@article.created_at) %> ago by <%= @article.user.get_name %>.</small></p>
		</div>
		<div class="row">
			<div class="col-md-7 mycontent-left">
				<div class="row">
					<div class="col-md-12">
						<%= @article.body.html_safe %>
					</div>
				</div>

				<div class="row">
					<div class="span7 clear-separator">
					</div>
				</div>

				<div class="row">
					<div class="col-md-12">
						<h5>Comments (<%= @comments.size %>) <%= link_to 'Leave a comment', new_article_comment_path(:article_slug => @article.slug, :article_id => @article.id) %></h5>
						<% if !user_signed_in? %>
							<small><span class="text-info">(You must be signed in to leave a comment.)</span></small>
						<% end %>

						</p>
					<% if !@comments.blank? %>

						<% @comments.each do |comment| %>
							<p><%= comment.text %><br />
								<small><span class="text-info">Submitted: <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.get_name %> </span></small></p>
								<% if comment != @comments.last %>
		  								<hr />
		  						<% end %>
						<% end %>
					<% else %>
						<p>Be the first, <%= link_to 'leave a comment', new_article_comment_path(:article_slug => @article.slug, :article_id => @article.id) %>.</p>
					<% end %>
				</div>
			</div>
		</div>
		<div class="col-md-4">
			<div class="row">
				<div class="col-md-12">
					<% if site_admin_logged_in? %>
						<h4>Admin Options</h4>
						<p><%= link_to "Edit Article", edit_article_path(@article.slug) %></p>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</section>