config/routes.rb
Allaboard::Application.routes.draw do

  root  'static_pages#new_home'

  get 'boards/suggest', to: 'boards#suggestion'
  post 'boards/suggestion/create', to: 'boards#suggestion_create'
  devise_for :users
  match '/help',  to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  post '/contact/send', to: 'static_pages#send_contact_message'
  match '/existing', to: 'static_pages#existing_members', via: 'get'
  match '/interested', to: 'static_pages#interested_member', via: 'get'
  match '/new_home', to: 'static_pages#new_home', via: 'get'
  match '/community', to: 'static_pages#community', via: 'get'

  resources :users
  resources :parent_organizations do
    collection do
      post 'import'
    end
  end

  resources :reviews, only: [:new, :create]
  resources :events, only: [:index, :show], param: :slug
  resources :reviews
  #resources :comments, :only => [:destroy, :show, :edit, :update]

  resources :articles, param: :slug do
    resources :comments, :only => [:create, :new]
  end

  resources :categories
  resources :announcements, only: [:index]

  resources :boards, param: :slug do
    resources :reviews, only: [:index, :show, :new]
    resources :events, param: :slug
    resources :announcements
    get 'claim'
    get 'unclaim'
    post 'assign'
    post 'unassign'
  end

  resources :vendors
  resources :vendor_reviews

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base

  # perform validations
  validates :name, presence: true, length: { minimum: 3 }
  validates :board_id, presence: true

  # define associations
  belongs_to :board
  has_many :vendor_reviews, dependent: :destroy

  before_validation :add_http_to_url
  before_save :default_values

  def get_random_review
    reviews = self.vendor_reviews
    max = reviews.count
    index = [*0..max-1].sample
    reviews[index]
  end

  def get_average_rating
    self.vendor_reviews.sum(:rating)/self.vendor_reviews.size
  end

  protected

  # function to add the 'http' prefix to vendor website urls that do not have this value
  # makes assumption that all URLs will be http instead of https
  # code snippet borrowed from the interwebs
  def add_http_to_url
    if !self.website_url.blank?
      unless self.website_url[/\Ahttp:\/\//] || self.website_url[/\Ahttps:\/\//]
        self.website_url = "http://#{self.website_url}"
      end
    end
  end

  private

    def default_values
      self.capacity ||= 0
      self.cost ||= 0
    end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit, :update, :destroy]
  before_action :user_owns_board, :only => [:new, :create]
  before_action :user_owns_this_vendor, :only => [:edit, :update, :destroy]

  def index
    @vendors = Vendor.all.paginate(:page => params[:page], :per_page => 20).order('name')
  end

  # Show action. This will respond to /vendors/:id
  def show
    # Check to see that a valid vendor id was sent in. If not, redirect to vendors index page
    if @vendor = Vendor.find_by(id: params[:id])
      # A valid vendor was passed via :id
      # get all reviews associated with this vendor
      @reviews = @vendor.vendor_reviews.paginate(:page => params[:page], :per_page => 5).order('created_at DESC')
    else
      flash[:warning] = "The vendor you are looking for does not exist"
      redirect_to vendors_path
    end
  end

  def new
    @vendor = Vendor.new
    @all_boards = Board.all
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      flash[:success] = "Vendor added to directory."
      redirect_to vendor_path(@vendor)
    else
      render 'new'
    end
  end

  def edit
    @vendor = Vendor.find(params[:id])
    @all_boards = Board.all
  end

  def update
    @vendor = Vendor.find(params[:id])
    if @vendor.update_attributes(vendor_params)
      flash[:success] = "Vendor updated"
      redirect_to @vendor
    else
      render 'edit'
    end
  end

  def destroy
    Vendor.find(params[:id]).destroy
    flash[:success] = "The vendor has been deleted."
    redirect_to vendors_path
  end

  private
    def vendor_params
      params.require(:vendor).permit(:name, :address, :phone, :email, :contact, :board_id, :outdoor, :indoor, :capacity, :cost, :food, :catering, :website_url)
    end

    def suggestion_params
      params.require(:suggestion).permit(:suggested_vendor_name, :suggester_email)
    end

    def user_owns_board
      if current_user.admin
        return
      end
      if current_user.boards.blank?
        flash[:failure] = "You can only do that if you manage a board."
        redirect_to vendors_path
      end
    end

    def user_owns_this_vendor
      if current_user.admin
        return
      end
      @vendor = Vendor.find(params[:id])
      @board = current_user.boards.find(@vendor.board_id)
      if @board.nil?
        flash[:failure] = "You can only do that if you own this vendor."
        redirect_to vendors_path
      end
    end

end

app/views/vendors/_error_messages.html.erb
<% if @vendor.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@vendor.errors.count, "error") %>.
    </div>
    <ul>
    <% @vendor.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/vendors/_form.html.erb
<%= form_for (@vendor) do |f| %>
	<div class="form-group">
		<%= render 'error_messages' %>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :name, 'Vendor Name'%>
					<%= f.text_field :name, :placeholder=>"Vendor Name", class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :address, 'Address' %>
					<%= f.text_area :address, :rows=>5, :class=>'input-block-level form-control' %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :phone, 'Phone number'%>
					<%= f.text_field :phone, class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :email, 'Email Address'%>
					<%= f.text_field :email, class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :contact, 'Contact Person'%>
					<%= f.text_field :contact, class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :website_url, 'Website URL'%>
					<%= f.text_field :website_url, :placeholder=>"http://example.com", class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
						<div class="checkbox"><label><%= f.check_box :indoor %><%= f.label :indoor, 'This vendor does indoor events' %></label></div>
						<div class="checkbox"><label><%= f.check_box :outdoor %><%= f.label :outdoor, 'This vendor does outdoor events' %> </label></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :capacity, 'What is the vendor\'s capcity?'%>
					<%= f.text_field :capacity, class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :cost, 'How much did it cost your board to hire this vendor?'%>
					<%= f.text_field :cost, class:"form-control" %>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
						<div class="checkbox"><label><%= f.check_box :food %><%= f.label :indoor, 'This vendor allows food at their venue' %></label></div>
						<div class="checkbox"><label><%= f.check_box :catering %><%= f.label :outdoor, 'This vendor allows outside catering' %> </label></div>
				</div>
			</div>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group">
					<%= f.label :board_id, 'Select your board'%>
					<%= f.collection_select :board_id, Board.all, :id, :name, {prompt: true}, {class: "form-control"} %>
				</div>
			</div>
		</div>

		<div class="clearfix"></div>

		<div class="row">
			<div class="col-md-6">
				<%= f.submit "Save", class: "btn btn-primary" %>&nbsp;<%= link_to 'Cancel', vendors_path %>
			</div>
		</div>
	</div>
<% end %>

app/views/vendors/_vendor.html.erb
<tr>
  <td><%= link_to vendor.name, vendor_path(vendor) %></td>
  <td><%= link_to vendor.board_id, vendor_path(vendor) %></td>
  <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
  <td><%= link_to 'Delete', vendor_path(vendor), method: :delete, data: { confirm: "Are you should you want to delete this vendor?" } %></td>
</tr>

app/views/vendors/edit.html.erb
<% provide(:title, "Edit Vendor details for " + @vendor.name + ": ") %>
<%= render 'shared/header' %>

<section>
	<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 class="section-heading">Edit vendor details</h3>
      </div>
    </div>

		<div class="row text-muted">
			<div class="col-lg-12">
			     <p>Use the form below to edit vendor details.</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
					<%= render 'form'%>
			</div>
		</div>

	</div>
</section>

app/views/vendors/index.html.erb
<% provide(:title, "Event Spaces in Chicago:") %>
<%= render 'shared/header' %>

<section>
	<div class="container">
    <div class="row text-center">
      <div class="col-lg-12">
        <h2 class="section-heading">Event Space Directory</h2>
      </div>
    </div>

		<div class="row text-muted">
			<div class="col-lg-12">
			     <p>As with everything on this site, the list of low-cost or free event spaces is a community-driven directory of vendors that have been used or referred to by other board members.
						 This list will become increasingly useful as more vendors are added. Please use our link below to submit a vendor to our directory and if you have used an event space that is already listed, please add a review to help others learn more about your experience.</p>
			</div>
		</div>

		<div class="row">
      <div class="col-md-7 mycontent-left">
				<% if !@vendors.blank? %>
		      <table class="table table-hoever">
		        <thead>
		          <tr>
		            <th>Vendor Name</th>
		            <th>Reviewing Board</th>
		          </tr>
		        </thead>
		        <tbody>
		        <!--<%= render @vendors %>-->
		          <% @vendors.each do |vendor| %>
		            <% @board = Board.find(vendor.board_id) %>
		            <tr>
		              <td><%= link_to vendor.name, vendor_path(vendor) %><div class="star" data-score='<%= vendor.get_average_rating %>'></div></td>
		              <td><%= link_to @board.name, board_path(@board.slug) %></td>
		            </tr>
		          <% end %>
		        </tbody>
		      </table>
		    <% end %>
				<%= will_paginate @vendors, renderer: BootstrapPagination::Rails %>
			</div>
			<div class="col-md-3">
				<div class="row">
					<p><%= link_to 'Add an Event Space', new_vendor_path %></p>
					<span class="text-info"><small>Note that you have to be a board owner to submit a vendor to this list.</span> </small>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/vendors/new.html.erb
<% provide(:title, "Add a new Event Space vendor:") %>
<%= render 'shared/header' %>

<section>
	<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <h3 class="section-heading">Add an Event Space vendor to directory</h3>
      </div>
    </div>

		<div class="row text-muted">
			<div class="col-lg-12">
			     <p>Use the form below to add a new vendor to the directory.</p>
			</div>
		</div>

		<div class="row">
			<div class="col-md-8">
					<%= render 'form'%>
			</div>
		</div>

	</div>
</section>

app/views/vendors/show.html.erb
<% provide(:title, 'Community vendor: ' + @vendor.name + ' on') %>
<%= render 'shared/header' %>


<section>
	<div class="container">
		<div class="col-md-12 ">
			<h2 class="section-heading"><%= @vendor.name %></h2>

      <% if current_user && @vendor.board.board_admin?(current_user) %>
        <p><%= link_to "Edit this vendor", edit_vendor_path(@vendor) %></p>
        <p><%= link_to "Delete this vendor", vendor_path(@vendor), method: :delete, data: { confirm: "Do you want to delete this vendor?" } %></p>
      <% end %>
    </div>
  </div>
</section>

<aside>
  <div class="container">
		<div class="row">

      <div class="col-md-7 mycontent-left">
        <div class="row">
					<div class="col-md-12">
						<h4>Address</h4>
            <% if !@vendor.address.blank? %>
              <p><%= @vendor.address %></p>
            <% end %>

						<h4>Website</h4>
            <% if !@vendor.website_url.blank? %>
              <p><%= link_to @vendor.website_url, @vendor.website_url, :target => "_blank" %></p>
            <% end %>

            <h4>Phone number</h4>
            <% if !@vendor.phone.blank? %>
              <p><%= @vendor.phone %></p>
            <% end %>

            <h4>Contact email</h4>
            <% if !@vendor.email.blank? %>
              <p><%= @vendor.email %></p>
            <% end %>

            <h4>Indoor events</h4>
            <% if @vendor.indoor %>
              <p>Yes</p>
            <% else %>
              <p>No</p>
            <% end %>

            <h4>Outdoor events</h4>
            <% if @vendor.outdoor %>
              <p>Yes</p>
            <% else %>
              <p>No</p>
            <% end %>

            <h4>Capacity</h4>
            <p><%= @vendor.capacity %></p>

            <h4>Cost estimate for using this vendor</h4>
            <p><%= @vendor.cost %></p>

            <h4>Provides food</h4>
            <% if @vendor.food %>
              <p>Yes</p>
            <% else %>
              <p>No</p>
            <% end %>

            <h4>Allows outside catering</h4>
            <% if @vendor.catering %>
              <p>Yes</p>
            <% else %>
              <p>No</p>
            <% end %>

            <h4>Board who added this vendor</h4>
            <p><%= link_to @vendor.board.name, board_path(@vendor.board.slug) %></p>

          </div>
        </div>

        <p>Reviews (<%= @vendor.vendor_reviews.size %>) <span class='text-info'><small>Got thoughts on this vendor? <%= link_to "Write a review", new_vendor_review_path(:vendor_id => @vendor.id) %>. </small></span> </p>
        <div class="row">
          <div class="col-md-12">
            <% if !@reviews.blank? %>
              <% @reviews.each do |review| %>
                <div class="row">
                  <div class="col-md-12">
                    <blockquote>
                      <p><%= review.title %></p>
                      <% if site_admin_logged_in? %>
                        <p style="font-size:14px"><%= link_to "Edit this review", edit_vendor_review_path(review) %></p>
                        <p style="font-size:14px"><%= link_to "Delete this review", vendor_review_path(review), method: :delete, data: { confirm: "Do you want to delete this review?" } %></p>
                      <% end %>
                      <div class="star" data-score='<%= review.rating %>'></div>
                      <small>Submitted <%= time_ago_in_words(review.created_at) %> ago.</small>
                      <h5>Pros:</h5>
                      <p><%= review.pros %></p>
                      <h5>Cons:</h5>
                      <p><%= review.cons %></p>
                  </blockquote>
                  <%= will_paginate @reviews, renderer: BootstrapPagination::Rails %>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</aside>